// Shared constants and utilities for Minecraft clone

// Shared constants and utilities for Minecraft clone

const BLOCK_TYPES = {
  // Air and Technical
  AIR: 0,
  CAVE_AIR: 1,
  VOID_AIR: 2,

  // Natural Blocks
  GRASS_BLOCK: 3,
  DIRT: 4,
  COARSE_DIRT: 5,
  PODZOL: 6,
  MYCELIUM: 7,
  ROOTED_DIRT: 8,
  MUD: 9,
  CLAY: 10,
  SAND: 11,
  RED_SAND: 12,
  GRAVEL: 13,
  STONE: 14,
  GRANITE: 15,
  DIORITE: 16,
  ANDESITE: 17,
  DEEPSLATE: 18,
  CALCITE: 19,
  TUFF: 20,
  DRIPSTONE_BLOCK: 21,
  GRASS: 22,
  TALL_GRASS: 23,
  FERN: 24,
  LARGE_FERN: 25,
  DEAD_BUSH: 26,
  DANDELION: 27,
  POPPY: 28,
  BLUE_ORCHID: 29,
  ALLIUM: 30,
  AZURE_BLUET: 31,
  RED_TULIP: 32,
  ORANGE_TULIP: 33,
  WHITE_TULIP: 34,
  PINK_TULIP: 35,
  OXEYE_DAISY: 36,
  CORNFLOWER: 37,
  LILY_OF_THE_VALLEY: 38,
  SUNFLOWER: 39,
  LILAC: 40,
  ROSE_BUSH: 41,
  PEONY: 42,
  BROWN_MUSHROOM: 43,
  RED_MUSHROOM: 44,
  CRIMSON_FUNGUS: 45,
  WARPED_FUNGUS: 46,
  CRIMSON_ROOTS: 47,
  WARPED_ROOTS: 48,
  NETHER_SPROUTS: 49,
  WEEPING_VINES: 50,
  TWISTING_VINES: 51,
  SUGAR_CANE: 52,
  KELP: 53,
  SEAGRASS: 54,
  SEA_PICKLE: 55,
  BRAIN_CORAL: 56,
  BUBBLE_CORAL: 57,
  FIRE_CORAL: 58,
  HORN_CORAL: 59,
  TUBE_CORAL: 60,
  BRAIN_CORAL_BLOCK: 61,
  BUBBLE_CORAL_BLOCK: 62,
  FIRE_CORAL_BLOCK: 63,
  HORN_CORAL_BLOCK: 64,
  TUBE_CORAL_BLOCK: 65,
  BRAIN_CORAL_FAN: 66,
  BUBBLE_CORAL_FAN: 67,
  FIRE_CORAL_FAN: 68,
  HORN_CORAL_FAN: 69,
  TUBE_CORAL_FAN: 70,
  DEAD_BRAIN_CORAL_BLOCK: 71,
  DEAD_BUBBLE_CORAL_BLOCK: 72,
  DEAD_FIRE_CORAL_BLOCK: 73,
  DEAD_HORN_CORAL_BLOCK: 74,
  DEAD_TUBE_CORAL_BLOCK: 75,
  DEAD_BRAIN_CORAL_FAN: 76,
  DEAD_BUBBLE_CORAL_FAN: 77,
  DEAD_FIRE_CORAL_FAN: 78,
  DEAD_HORN_CORAL_FAN: 79,
  DEAD_TUBE_CORAL_FAN: 80,

  // Ores and Minerals
  COAL_ORE: 81,
  DEEPSLATE_COAL_ORE: 82,
  IRON_ORE: 83,
  DEEPSLATE_IRON_ORE: 84,
  COPPER_ORE: 85,
  DEEPSLATE_COPPER_ORE: 86,
  GOLD_ORE: 87,
  DEEPSLATE_GOLD_ORE: 88,
  REDSTONE_ORE: 89,
  DEEPSLATE_REDSTONE_ORE: 90,
  EMERALD_ORE: 91,
  DEEPSLATE_EMERALD_ORE: 92,
  LAPIS_ORE: 93,
  DEEPSLATE_LAPIS_ORE: 94,
  DIAMOND_ORE: 95,
  DEEPSLATE_DIAMOND_ORE: 96,
  NETHER_GOLD_ORE: 97,
  NETHER_QUARTZ_ORE: 98,
  ANCIENT_DEBRIS: 99,

  // Manufactured Blocks
  COBBLESTONE: 100,
  MOSSY_COBBLESTONE: 101,
  STONE_BRICKS: 102,
  MOSSY_STONE_BRICKS: 103,
  CRACKED_STONE_BRICKS: 104,
  CHISELED_STONE_BRICKS: 105,
  SMOOTH_STONE: 106,
  STONE_SLAB: 107,
  SMOOTH_STONE_SLAB: 108,
  SANDSTONE: 109,
  CHISELED_SANDSTONE: 110,
  CUT_SANDSTONE: 111,
  RED_SANDSTONE: 112,
  CHISELED_RED_SANDSTONE: 113,
  CUT_RED_SANDSTONE: 114,
  BRICKS: 115,
  PACKED_MUD: 116,
  MUD_BRICKS: 117,

  // Woods and Plants
  OAK_LOG: 118,
  SPRUCE_LOG: 119,
  BIRCH_LOG: 120,
  JUNGLE_LOG: 121,
  ACACIA_LOG: 122,
  DARK_OAK_LOG: 123,
  CRIMSON_STEM: 124,
  WARPED_STEM: 125,
  OAK_LEAVES: 126,
  SPRUCE_LEAVES: 127,
  BIRCH_LEAVES: 128,
  JUNGLE_LEAVES: 129,
  ACACIA_LEAVES: 130,
  DARK_OAK_LEAVES: 131,
  AZALEA_LEAVES: 132,
  FLOWERING_AZALEA_LEAVES: 133,
  OAK_PLANKS: 134,
  SPRUCE_PLANKS: 135,
  BIRCH_PLANKS: 136,
  JUNGLE_PLANKS: 137,
  ACACIA_PLANKS: 138,
  DARK_OAK_PLANKS: 139,
  CRIMSON_PLANKS: 140,
  WARPED_PLANKS: 141,
  OAK_SAPLING: 142,
  SPRUCE_SAPLING: 143,
  BIRCH_SAPLING: 144,
  JUNGLE_SAPLING: 145,
  ACACIA_SAPLING: 146,
  DARK_OAK_SAPLING: 147,
  AZALEA: 148,
  FLOWERING_AZALEA: 149,

  // Wool and Carpets
  WHITE_WOOL: 150,
  ORANGE_WOOL: 151,
  MAGENTA_WOOL: 152,
  LIGHT_BLUE_WOOL: 153,
  YELLOW_WOOL: 154,
  LIME_WOOL: 155,
  PINK_WOOL: 156,
  GRAY_WOOL: 157,
  LIGHT_GRAY_WOOL: 158,
  CYAN_WOOL: 159,
  PURPLE_WOOL: 160,
  BLUE_WOOL: 161,
  BROWN_WOOL: 162,
  GREEN_WOOL: 163,
  RED_WOOL: 164,
  BLACK_WOOL: 165,
  WHITE_CARPET: 166,
  ORANGE_CARPET: 167,
  MAGENTA_CARPET: 168,
  LIGHT_BLUE_CARPET: 169,
  YELLOW_CARPET: 170,
  LIME_CARPET: 171,
  PINK_CARPET: 172,
  GRAY_CARPET: 173,
  LIGHT_GRAY_CARPET: 174,
  CYAN_CARPET: 175,
  PURPLE_CARPET: 176,
  BLUE_CARPET: 177,
  BROWN_CARPET: 178,
  GREEN_CARPET: 179,
  RED_CARPET: 180,
  BLACK_CARPET: 181,

  // Glass and Transparent
  GLASS: 182,
  WHITE_STAINED_GLASS: 183,
  ORANGE_STAINED_GLASS: 184,
  MAGENTA_STAINED_GLASS: 185,
  LIGHT_BLUE_STAINED_GLASS: 186,
  YELLOW_STAINED_GLASS: 187,
  LIME_STAINED_GLASS: 188,
  PINK_STAINED_GLASS: 189,
  GRAY_STAINED_GLASS: 190,
  LIGHT_GRAY_STAINED_GLASS: 191,
  CYAN_STAINED_GLASS: 192,
  PURPLE_STAINED_GLASS: 193,
  BLUE_STAINED_GLASS: 194,
  BROWN_STAINED_GLASS: 195,
  GREEN_STAINED_GLASS: 196,
  RED_STAINED_GLASS: 197,
  BLACK_STAINED_GLASS: 198,
  GLASS_PANE: 199,
  WHITE_STAINED_GLASS_PANE: 200,
  ORANGE_STAINED_GLASS_PANE: 201,
  MAGENTA_STAINED_GLASS_PANE: 202,
  LIGHT_BLUE_STAINED_GLASS_PANE: 203,
  YELLOW_STAINED_GLASS_PANE: 204,
  LIME_STAINED_GLASS_PANE: 205,
  PINK_STAINED_GLASS_PANE: 206,
  GRAY_STAINED_GLASS_PANE: 207,
  LIGHT_GRAY_STAINED_GLASS_PANE: 208,
  CYAN_STAINED_GLASS_PANE: 209,
  PURPLE_STAINED_GLASS_PANE: 210,
  BLUE_STAINED_GLASS_PANE: 211,
  BROWN_STAINED_GLASS_PANE: 212,
  GREEN_STAINED_GLASS_PANE: 213,
  RED_STAINED_GLASS_PANE: 214,
  BLACK_STAINED_GLASS_PANE: 215,

  // Nether Blocks
  NETHERRACK: 216,
  NETHER_BRICKS: 217,
  CRACKED_NETHER_BRICKS: 218,
  CHISELED_NETHER_BRICKS: 219,
  NETHER_WART_BLOCK: 220,
  WARPED_WART_BLOCK: 221,
  SOUL_SAND: 222,
  SOUL_SOIL: 223,
  BASALT: 224,
  POLISHED_BASALT: 225,
  SMOOTH_BASALT: 226,
  BLACKSTONE: 227,
  GILDED_BLACKSTONE: 228,
  POLISHED_BLACKSTONE: 229,
  CHISELED_POLISHED_BLACKSTONE: 230,
  POLISHED_BLACKSTONE_BRICKS: 231,
  CRACKED_POLISHED_BLACKSTONE_BRICKS: 232,
  MAGMA_BLOCK: 233,
  CRYING_OBSIDIAN: 234,
  OBSIDIAN: 235,
  BEDROCK: 236,

  // Liquids
  WATER: 237,
  LAVA: 238,

  // Functional Blocks
  CRAFTING_TABLE: 239,
  FURNACE: 240,
  CHEST: 241,
  ENDER_CHEST: 242,
  JUKEBOX: 243,
  ENCHANTING_TABLE: 244,
  BREWING_STAND: 245,
  CAULDRON: 246,
  HOPPER: 247,
  DROPPER: 248,
  DISPENSER: 249,
  PISTON: 250,
  STICKY_PISTON: 251,
  TNT: 252,
  BOOKSHELF: 253,
  LECTERN: 254,
  BELL: 255,
  TARGET: 256,
  LOOM: 257,
  COMPOSTER: 258,
  BARREL: 259,
  SMOKER: 260,
  BLAST_FURNACE: 261,
  CARTOGRAPHY_TABLE: 262,
  FLETCHING_TABLE: 263,
  SMITHING_TABLE: 264,
  GRINDSTONE: 265,
  STONECUTTER: 266,
  NOTE_BLOCK: 267,
  IRON_BARS: 268,
  CHAIN: 269,
  LADDER: 270,
  SCAFFOLDING: 271,
  LANTERN: 272,
  SOUL_LANTERN: 273,
  CAMPFIRE: 274,
  SOUL_CAMPFIRE: 275,
  BEEHIVE: 276,
  BEE_NEST: 277,
  LODestone: 278,
  RESPAWN_ANCHOR: 279,
  LIGHTNING_ROD: 280,
  CONDUIT: 281,
  BEACON: 282,

  // Redstone Components
  REDSTONE_WIRE: 283,
  REDSTONE_TORCH: 284,
  REDSTONE_LAMP: 285,
  REPEATER: 286,
  COMPARATOR: 287,
  LEVER: 288,
  STONE_BUTTON: 289,
  OAK_BUTTON: 290,
  SPRUCE_BUTTON: 291,
  BIRCH_BUTTON: 292,
  JUNGLE_BUTTON: 293,
  ACACIA_BUTTON: 294,
  DARK_OAK_BUTTON: 295,
  CRIMSON_BUTTON: 296,
  WARPED_BUTTON: 297,
  STONE_PRESSURE_PLATE: 298,
  OAK_PRESSURE_PLATE: 299,
  SPRUCE_PRESSURE_PLATE: 300,
  BIRCH_PRESSURE_PLATE: 301,
  JUNGLE_PRESSURE_PLATE: 302,
  ACACIA_PRESSURE_PLATE: 303,
  DARK_OAK_PRESSURE_PLATE: 304,
  CRIMSON_PRESSURE_PLATE: 305,
  WARPED_PRESSURE_PLATE: 306,
  HEAVY_WEIGHTED_PRESSURE_PLATE: 307,
  LIGHT_WEIGHTED_PRESSURE_PLATE: 308,
  TRIPWIRE_HOOK: 309,
  TRAPPED_CHEST: 310,
  DAYLIGHT_DETECTOR: 311,
  RAIL: 312,
  POWERED_RAIL: 313,
  DETECTOR_RAIL: 314,
  ACTIVATOR_RAIL: 315,
  MINECART: 316,
  HOPPER_MINECART: 317,
  CHEST_MINECART: 318,
  FURNACE_MINECART: 319,
  TNT_MINECART: 320,
  COMMAND_BLOCK_MINECART: 321,

  // Command Blocks
  COMMAND_BLOCK: 322,
  CHAIN_COMMAND_BLOCK: 323,
  REPEATING_COMMAND_BLOCK: 324,

  // End Blocks
  END_STONE: 325,
  END_STONE_BRICKS: 326,
  PURPUR_BLOCK: 327,
  PURPUR_PILLAR: 328,
  END_ROD: 329,
  DRAGON_EGG: 330,

  // Slabs and Stairs (subset - many more exist)
  OAK_SLAB: 331,
  SPRUCE_SLAB: 332,
  BIRCH_SLAB: 333,
  JUNGLE_SLAB: 334,
  ACACIA_SLAB: 335,
  DARK_OAK_SLAB: 336,
  STONE_SLAB: 337,
  SMOOTH_STONE_SLAB: 338,
  SANDSTONE_SLAB: 339,
  CUT_SANDSTONE_SLAB: 340,
  PETRIFIED_OAK_SLAB: 341,
  COBBLESTONE_SLAB: 342,
  BRICK_SLAB: 343,
  STONE_BRICK_SLAB: 344,
  NETHER_BRICK_SLAB: 345,
  QUARTZ_SLAB: 346,
  RED_SANDSTONE_SLAB: 347,
  CUT_RED_SANDSTONE_SLAB: 348,
  PURPUR_SLAB: 349,
  PRISMARINE_SLAB: 350,
  PRISMARINE_BRICK_SLAB: 351,
  DARK_PRISMARINE_SLAB: 352,
  OAK_STAIRS: 353,
  COBBLESTONE_STAIRS: 354,
  BRICK_STAIRS: 355,
  STONE_BRICK_STAIRS: 356,
  NETHER_BRICK_STAIRS: 357,
  SANDSTONE_STAIRS: 358,
  SPRUCE_STAIRS: 359,
  BIRCH_STAIRS: 360,
  JUNGLE_STAIRS: 361,
  QUARTZ_STAIRS: 362,
  ACACIA_STAIRS: 363,
  DARK_OAK_STAIRS: 364,
  PRISMARINE_STAIRS: 365,
  PRISMARINE_BRICK_STAIRS: 366,
  DARK_PRISMARINE_STAIRS: 367,
  RED_SANDSTONE_STAIRS: 368,
  PURPUR_STAIRS: 369,

  // Additional blocks (continuing numbering)
  QUARTZ_BLOCK: 370,
  CHISELED_QUARTZ_BLOCK: 371,
  QUARTZ_PILLAR: 372,
  QUARTZ_BRICKS: 373,
  SMOOTH_QUARTZ: 374,
  PRISMARINE: 375,
  PRISMARINE_BRICKS: 376,
  DARK_PRISMARINE: 377,
  SEA_LANTERN: 378,
  SHROOMLIGHT: 379,
  HONEY_BLOCK: 380,
  HONEYCOMB_BLOCK: 381,
  SLIME_BLOCK: 382,
  BONE_BLOCK: 383,
  NETHERITE_BLOCK: 384,
  ANCIENT_DEBRIS: 385,
  CRYING_OBSIDIAN: 386,
  RESPAWN_ANCHOR: 387,
  LODESTONE: 388,
  LIGHT_BLOCK: 389,
  AMETHYST_BLOCK: 390,
  BUDDING_AMETHYST: 391,
  AMETHYST_CLUSTER: 392,
  LARGE_AMETHYST_BUD: 393,
  MEDIUM_AMETHYST_BUD: 394,
  SMALL_AMETHYST_BUD: 395,
  TINTED_GLASS: 396,
  POWDER_SNOW: 397,
  SCULK: 398,
  SCULK_VEIN: 399,
  SCULK_CATALYST: 400,
  SCULK_SHRIEKER: 401,
  REINFORCED_DEEPSLATE: 402,
  COPPER_BLOCK: 403,
  EXPOSED_COPPER: 404,
  WEATHERED_COPPER: 405,
  OXIDIZED_COPPER: 406,
  CUT_COPPER: 407,
  EXPOSED_CUT_COPPER: 408,
  WEATHERED_CUT_COPPER: 409,
  OXIDIZED_CUT_COPPER: 410,
  WAXED_COPPER_BLOCK: 411,
  WAXED_EXPOSED_COPPER: 412,
  WAXED_WEATHERED_COPPER: 413,
  WAXED_OXIDIZED_COPPER: 414,
  WAXED_CUT_COPPER: 415,
  WAXED_EXPOSED_CUT_COPPER: 416,
  WAXED_WEATHERED_CUT_COPPER: 417,
  WAXED_OXIDIZED_CUT_COPPER: 418,
  RAW_IRON_BLOCK: 419,
  RAW_COPPER_BLOCK: 420,
  RAW_GOLD_BLOCK: 421,
  MANGROVE_LOG: 422,
  MANGROVE_WOOD: 423,
  STRIPPED_MANGROVE_LOG: 424,
  STRIPPED_MANGROVE_WOOD: 425,
  MANGROVE_PLANKS: 426,
  MANGROVE_LEAVES: 427,
  MANGROVE_PROPAGULE: 428,
  MUDDY_MANGROVE_ROOTS: 429,
  MANGROVE_ROOTS: 430,
  BAMBOO_BLOCK: 431,
  STRIPPED_BAMBOO_BLOCK: 432,
  BAMBOO: 433,
  BAMBOO_SAPLING: 434,
  BAMBOO_MOSAIC: 435,
  CHERRY_LOG: 436,
  CHERRY_WOOD: 437,
  STRIPPED_CHERRY_LOG: 438,
  STRIPPED_CHERRY_WOOD: 439,
  CHERRY_PLANKS: 440,
  CHERRY_LEAVES: 441,
  CHERRY_SAPLING: 442,
  PINK_PETALS: 443,
  SPORE_BLOSSOM: 444,
  AZALEA: 445,
  FLOWERING_AZALEA: 446,
  MOSS_CARPET: 447,
  PINK_WOOL: 448,
  MAGENTA_WOOL: 449,
  PURPLE_WOOL: 450,
  BLUE_WOOL: 451,
  BROWN_WOOL: 452,
  GREEN_WOOL: 453,
  RED_WOOL: 454,
  BLACK_WOOL: 455,
  GRAY_WOOL: 456,
  LIGHT_GRAY_WOOL: 457,
  CYAN_WOOL: 458,
  LIGHT_BLUE_WOOL: 459,
  LIME_WOOL: 460,
  YELLOW_WOOL: 461,
  ORANGE_WOOL: 462,
  WHITE_WOOL: 463,
  PINK_CARPET: 464,
  MAGENTA_CARPET: 465,
  PURPLE_CARPET: 466,
  BLUE_CARPET: 467,
  BROWN_CARPET: 468,
  GREEN_CARPET: 469,
  RED_CARPET: 470,
  BLACK_CARPET: 471,
  GRAY_CARPET: 472,
  LIGHT_GRAY_CARPET: 473,
  CYAN_CARPET: 474,
  LIGHT_BLUE_CARPET: 475,
  LIME_CARPET: 476,
  YELLOW_CARPET: 477,
  ORANGE_CARPET: 478,
  WHITE_CARPET: 479,
  CALCITE: 480,
  TUFF: 481,
  DRIPSTONE_BLOCK: 482,
  ROOTED_DIRT: 483,
  HANGING_ROOTS: 484,
  MOSS_BLOCK: 485,
  BIG_DRIPLEAF: 486,
  BIG_DRIPLEAF_STEM: 487,
  SMALL_DRIPLEAF: 488,
  SPORE_BLOSSOM: 489,
  CAVE_VINES: 490,
  CAVE_VINES_PLANT: 491,
  GLOW_LICHEN: 492,
  GLOW_BERRIES: 493,
  POINTED_DRIPSTONE: 494,
  SCULK_SENSOR: 495,
  CALIBRATED_SCULK_SENSOR: 496,
  FROGSPAWN: 497,
  FROG_LIGHT: 498,
  OCHRE_FROGLIGHT: 499,
  VERDANT_FROGLIGHT: 500,
  PEARLESCENT_FROGLIGHT: 501,
  MANGROVE_LOG: 502,
  MANGROVE_WOOD: 503,
  STRIPPED_MANGROVE_LOG: 504,
  STRIPPED_MANGROVE_WOOD: 505,
  MANGROVE_PLANKS: 506,
  MANGROVE_BUTTON: 507,
  MANGROVE_DOOR: 508,
  MANGROVE_FENCE: 509,
  MANGROVE_FENCE_GATE: 510,
  MANGROVE_PRESSURE_PLATE: 511,
  MANGROVE_SIGN: 512,
  MANGROVE_SLAB: 513,
  MANGROVE_STAIRS: 514,
  MANGROVE_TRAPDOOR: 515,
  BAMBOO_BLOCK: 516,
  STRIPPED_BAMBOO_BLOCK: 517,
  BAMBOO_BUTTON: 518,
  BAMBOO_DOOR: 519,
  BAMBOO_FENCE: 520,
  BAMBOO_FENCE_GATE: 521,
  BAMBOO_MOSAIC: 522,
  BAMBOO_MOSAIC_SLAB: 523,
  BAMBOO_MOSAIC_STAIRS: 524,
  BAMBOO_PLANKS: 525,
  BAMBOO_PRESSURE_PLATE: 526,
  BAMBOO_SIGN: 527,
  BAMBOO_SLAB: 528,
  BAMBOO_STAIRS: 529,
  BAMBOO_TRAPDOOR: 530,
  CHERRY_BUTTON: 531,
  CHERRY_DOOR: 532,
  CHERRY_FENCE: 533,
  CHERRY_FENCE_GATE: 534,
  CHERRY_PLANKS: 535,
  CHERRY_PRESSURE_PLATE: 536,
  CHERRY_SIGN: 537,
  CHERRY_SLAB: 538,
  CHERRY_STAIRS: 539,
  CHERRY_TRAPDOOR: 540,
  CRIMSON_BUTTON: 541,
  CRIMSON_DOOR: 542,
  CRIMSON_FENCE: 543,
  CRIMSON_FENCE_GATE: 544,
  CRIMSON_PLANKS: 545,
  CRIMSON_PRESSURE_PLATE: 546,
  CRIMSON_SIGN: 547,
  CRIMSON_SLAB: 548,
  CRIMSON_STAIRS: 549,
  CRIMSON_TRAPDOOR: 550,
  WARPED_BUTTON: 551,
  WARPED_DOOR: 552,
  WARPED_FENCE: 553,
  WARPED_FENCE_GATE: 554,
  WARPED_PLANKS: 555,
  WARPED_PRESSURE_PLATE: 556,
  WARPED_SIGN: 557,
  WARPED_SLAB: 558,
  WARPED_STAIRS: 559,
  WARPED_TRAPDOOR: 560,
  OAK_BUTTON: 561,
  OAK_DOOR: 562,
  OAK_FENCE: 563,
  OAK_FENCE_GATE: 564,
  OAK_PLANKS: 565,
  OAK_PRESSURE_PLATE: 566,
  OAK_SIGN: 567,
  OAK_SLAB: 568,
  OAK_STAIRS: 569,
  OAK_TRAPDOOR: 570,
  SPRUCE_BUTTON: 571,
  SPRUCE_DOOR: 572,
  SPRUCE_FENCE: 573,
  SPRUCE_FENCE_GATE: 574,
  SPRUCE_PLANKS: 575,
  SPRUCE_PRESSURE_PLATE: 576,
  SPRUCE_SIGN: 577,
  SPRUCE_SLAB: 578,
  SPRUCE_STAIRS: 579,
  SPRUCE_TRAPDOOR: 580,
  BIRCH_BUTTON: 581,
  BIRCH_DOOR: 582,
  BIRCH_FENCE: 583,
  BIRCH_FENCE_GATE: 584,
  BIRCH_PLANKS: 585,
  BIRCH_PRESSURE_PLATE: 586,
  BIRCH_SIGN: 587,
  BIRCH_SLAB: 588,
  BIRCH_STAIRS: 589,
  BIRCH_TRAPDOOR: 590,
  JUNGLE_BUTTON: 591,
  JUNGLE_DOOR: 592,
  JUNGLE_FENCE: 593,
  JUNGLE_FENCE_GATE: 594,
  JUNGLE_PLANKS: 595,
  JUNGLE_PRESSURE_PLATE: 596,
  JUNGLE_SIGN: 597,
  JUNGLE_SLAB: 598,
  JUNGLE_STAIRS: 599,
  JUNGLE_TRAPDOOR: 600,
  ACACIA_BUTTON: 601,
  ACACIA_DOOR: 602,
  ACACIA_FENCE: 603,
  ACACIA_FENCE_GATE: 604,
  ACACIA_PLANKS: 605,
  ACACIA_PRESSURE_PLATE: 606,
  ACACIA_SIGN: 607,
  ACACIA_SLAB: 608,
  ACACIA_STAIRS: 609,
  ACACIA_TRAPDOOR: 610,
  DARK_OAK_BUTTON: 611,
  DARK_OAK_DOOR: 612,
  DARK_OAK_FENCE: 613,
  DARK_OAK_FENCE_GATE: 614,
  DARK_OAK_PLANKS: 615,
  DARK_OAK_PRESSURE_PLATE: 616,
  DARK_OAK_SIGN: 617,
  DARK_OAK_SLAB: 618,
  DARK_OAK_STAIRS: 619,
  DARK_OAK_TRAPDOOR: 620,
  // Note: This is a substantial subset of vanilla blocks. Full 1.21.10 has ~800+ blocks
  // Additional blocks would include more variants, walls, banners, etc.
};

// Block properties for mining, tools, and behavior
const BLOCK_PROPERTIES = {
  [BLOCK_TYPES.AIR]: { hardness: 0, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.CAVE_AIR]: { hardness: 0, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.VOID_AIR]: { hardness: 0, tool: null, drops: null, transparent: true },

  // Natural blocks
  [BLOCK_TYPES.GRASS_BLOCK]: { hardness: 0.6, tool: 'shovel', drops: BLOCK_TYPES.DIRT, transparent: false },
  [BLOCK_TYPES.DIRT]: { hardness: 0.5, tool: 'shovel', drops: BLOCK_TYPES.DIRT, transparent: false },
  [BLOCK_TYPES.COARSE_DIRT]: { hardness: 0.5, tool: 'shovel', drops: BLOCK_TYPES.COARSE_DIRT, transparent: false },
  [BLOCK_TYPES.PODZOL]: { hardness: 0.5, tool: 'shovel', drops: BLOCK_TYPES.DIRT, transparent: false },
  [BLOCK_TYPES.MYCELIUM]: { hardness: 0.6, tool: 'shovel', drops: BLOCK_TYPES.DIRT, transparent: false },
  [BLOCK_TYPES.ROOTED_DIRT]: { hardness: 0.5, tool: 'shovel', drops: BLOCK_TYPES.DIRT, transparent: false },
  [BLOCK_TYPES.MUD]: { hardness: 0.5, tool: 'shovel', drops: BLOCK_TYPES.MUD, transparent: false },
  [BLOCK_TYPES.CLAY]: { hardness: 0.6, tool: 'shovel', drops: BLOCK_TYPES.CLAY, transparent: false },
  [BLOCK_TYPES.SAND]: { hardness: 0.5, tool: 'shovel', drops: BLOCK_TYPES.SAND, transparent: false },
  [BLOCK_TYPES.RED_SAND]: { hardness: 0.5, tool: 'shovel', drops: BLOCK_TYPES.RED_SAND, transparent: false },
  [BLOCK_TYPES.GRAVEL]: { hardness: 0.6, tool: 'shovel', drops: BLOCK_TYPES.GRAVEL, transparent: false },
  [BLOCK_TYPES.STONE]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.COBBLESTONE, transparent: false },
  [BLOCK_TYPES.GRANITE]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.GRANITE, transparent: false },
  [BLOCK_TYPES.DIORITE]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.DIORITE, transparent: false },
  [BLOCK_TYPES.ANDESITE]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.ANDESITE, transparent: false },
  [BLOCK_TYPES.DEEPSLATE]: { hardness: 3.0, tool: 'pickaxe', drops: BLOCK_TYPES.COBBLESTONE, transparent: false },
  [BLOCK_TYPES.CALCITE]: { hardness: 0.75, tool: 'pickaxe', drops: BLOCK_TYPES.CALCITE, transparent: false },
  [BLOCK_TYPES.TUFF]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.TUFF, transparent: false },
  [BLOCK_TYPES.DRIPSTONE_BLOCK]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.DRIPSTONE_BLOCK, transparent: false },

  // Ores
  [BLOCK_TYPES.COAL_ORE]: { hardness: 3.0, tool: 'pickaxe', drops: 'coal', transparent: false },
  [BLOCK_TYPES.DEEPSLATE_COAL_ORE]: { hardness: 4.5, tool: 'pickaxe', drops: 'coal', transparent: false },
  [BLOCK_TYPES.IRON_ORE]: { hardness: 3.0, tool: 'pickaxe', drops: 'iron_ore', transparent: false },
  [BLOCK_TYPES.DEEPSLATE_IRON_ORE]: { hardness: 4.5, tool: 'pickaxe', drops: 'iron_ore', transparent: false },
  [BLOCK_TYPES.COPPER_ORE]: { hardness: 3.0, tool: 'pickaxe', drops: 'copper_ore', transparent: false },
  [BLOCK_TYPES.DEEPSLATE_COPPER_ORE]: { hardness: 4.5, tool: 'pickaxe', drops: 'copper_ore', transparent: false },
  [BLOCK_TYPES.GOLD_ORE]: { hardness: 3.0, tool: 'pickaxe', drops: 'gold_ore', transparent: false },
  [BLOCK_TYPES.DEEPSLATE_GOLD_ORE]: { hardness: 4.5, tool: 'pickaxe', drops: 'gold_ore', transparent: false },
  [BLOCK_TYPES.REDSTONE_ORE]: { hardness: 3.0, tool: 'pickaxe', drops: 'redstone', transparent: false },
  [BLOCK_TYPES.DEEPSLATE_REDSTONE_ORE]: { hardness: 4.5, tool: 'pickaxe', drops: 'redstone', transparent: false },
  [BLOCK_TYPES.EMERALD_ORE]: { hardness: 3.0, tool: 'pickaxe', drops: 'emerald', transparent: false },
  [BLOCK_TYPES.DEEPSLATE_EMERALD_ORE]: { hardness: 4.5, tool: 'pickaxe', drops: 'emerald', transparent: false },
  [BLOCK_TYPES.LAPIS_ORE]: { hardness: 3.0, tool: 'pickaxe', drops: 'lapis_lazuli', transparent: false },
  [BLOCK_TYPES.DEEPSLATE_LAPIS_ORE]: { hardness: 4.5, tool: 'pickaxe', drops: 'lapis_lazuli', transparent: false },
  [BLOCK_TYPES.DIAMOND_ORE]: { hardness: 3.0, tool: 'pickaxe', drops: 'diamond', transparent: false },
  [BLOCK_TYPES.DEEPSLATE_DIAMOND_ORE]: { hardness: 4.5, tool: 'pickaxe', drops: 'diamond', transparent: false },
  [BLOCK_TYPES.NETHER_GOLD_ORE]: { hardness: 3.0, tool: 'pickaxe', drops: 'gold_nugget', transparent: false },
  [BLOCK_TYPES.NETHER_QUARTZ_ORE]: { hardness: 3.0, tool: 'pickaxe', drops: 'quartz', transparent: false },
  [BLOCK_TYPES.ANCIENT_DEBRIS]: { hardness: 30.0, tool: 'pickaxe', drops: 'netherite_scrap', transparent: false },

  // Manufactured blocks
  [BLOCK_TYPES.COBBLESTONE]: { hardness: 2.0, tool: 'pickaxe', drops: BLOCK_TYPES.COBBLESTONE, transparent: false },
  [BLOCK_TYPES.MOSSY_COBBLESTONE]: { hardness: 2.0, tool: 'pickaxe', drops: BLOCK_TYPES.MOSSY_COBBLESTONE, transparent: false },
  [BLOCK_TYPES.STONE_BRICKS]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.STONE_BRICKS, transparent: false },
  [BLOCK_TYPES.MOSSY_STONE_BRICKS]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.MOSSY_STONE_BRICKS, transparent: false },
  [BLOCK_TYPES.CRACKED_STONE_BRICKS]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.CRACKED_STONE_BRICKS, transparent: false },
  [BLOCK_TYPES.CHISELED_STONE_BRICKS]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.CHISELED_STONE_BRICKS, transparent: false },
  [BLOCK_TYPES.SMOOTH_STONE]: { hardness: 2.0, tool: 'pickaxe', drops: BLOCK_TYPES.SMOOTH_STONE, transparent: false },
  [BLOCK_TYPES.SANDSTONE]: { hardness: 0.8, tool: 'pickaxe', drops: BLOCK_TYPES.SANDSTONE, transparent: false },
  [BLOCK_TYPES.RED_SANDSTONE]: { hardness: 0.8, tool: 'pickaxe', drops: BLOCK_TYPES.RED_SANDSTONE, transparent: false },
  [BLOCK_TYPES.BRICKS]: { hardness: 2.0, tool: 'pickaxe', drops: BLOCK_TYPES.BRICKS, transparent: false },
  [BLOCK_TYPES.PACKED_MUD]: { hardness: 1.0, tool: 'pickaxe', drops: BLOCK_TYPES.PACKED_MUD, transparent: false },
  [BLOCK_TYPES.MUD_BRICKS]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.MUD_BRICKS, transparent: false },

  // Wood blocks
  [BLOCK_TYPES.OAK_LOG]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.OAK_LOG, transparent: false },
  [BLOCK_TYPES.SPRUCE_LOG]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.SPRUCE_LOG, transparent: false },
  [BLOCK_TYPES.BIRCH_LOG]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.BIRCH_LOG, transparent: false },
  [BLOCK_TYPES.JUNGLE_LOG]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.JUNGLE_LOG, transparent: false },
  [BLOCK_TYPES.ACACIA_LOG]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.ACACIA_LOG, transparent: false },
  [BLOCK_TYPES.DARK_OAK_LOG]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.DARK_OAK_LOG, transparent: false },
  [BLOCK_TYPES.CRIMSON_STEM]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.CRIMSON_STEM, transparent: false },
  [BLOCK_TYPES.WARPED_STEM]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.WARPED_STEM, transparent: false },
  [BLOCK_TYPES.OAK_LEAVES]: { hardness: 0.2, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.SPRUCE_LEAVES]: { hardness: 0.2, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.BIRCH_LEAVES]: { hardness: 0.2, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.JUNGLE_LEAVES]: { hardness: 0.2, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.ACACIA_LEAVES]: { hardness: 0.2, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.DARK_OAK_LEAVES]: { hardness: 0.2, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.AZALEA_LEAVES]: { hardness: 0.2, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.FLOWERING_AZALEA_LEAVES]: { hardness: 0.2, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.OAK_PLANKS]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.OAK_PLANKS, transparent: false },
  [BLOCK_TYPES.SPRUCE_PLANKS]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.SPRUCE_PLANKS, transparent: false },
  [BLOCK_TYPES.BIRCH_PLANKS]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.BIRCH_PLANKS, transparent: false },
  [BLOCK_TYPES.JUNGLE_PLANKS]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.JUNGLE_PLANKS, transparent: false },
  [BLOCK_TYPES.ACACIA_PLANKS]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.ACACIA_PLANKS, transparent: false },
  [BLOCK_TYPES.DARK_OAK_PLANKS]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.DARK_OAK_PLANKS, transparent: false },
  [BLOCK_TYPES.CRIMSON_PLANKS]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.CRIMSON_PLANKS, transparent: false },
  [BLOCK_TYPES.WARPED_PLANKS]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.WARPED_PLANKS, transparent: false },

  // Wool
  [BLOCK_TYPES.WHITE_WOOL]: { hardness: 0.8, tool: null, drops: BLOCK_TYPES.WHITE_WOOL, transparent: false },
  [BLOCK_TYPES.ORANGE_WOOL]: { hardness: 0.8, tool: null, drops: BLOCK_TYPES.ORANGE_WOOL, transparent: false },
  [BLOCK_TYPES.MAGENTA_WOOL]: { hardness: 0.8, tool: null, drops: BLOCK_TYPES.MAGENTA_WOOL, transparent: false },
  [BLOCK_TYPES.LIGHT_BLUE_WOOL]: { hardness: 0.8, tool: null, drops: BLOCK_TYPES.LIGHT_BLUE_WOOL, transparent: false },
  [BLOCK_TYPES.YELLOW_WOOL]: { hardness: 0.8, tool: null, drops: BLOCK_TYPES.YELLOW_WOOL, transparent: false },
  [BLOCK_TYPES.LIME_WOOL]: { hardness: 0.8, tool: null, drops: BLOCK_TYPES.LIME_WOOL, transparent: false },
  [BLOCK_TYPES.PINK_WOOL]: { hardness: 0.8, tool: null, drops: BLOCK_TYPES.PINK_WOOL, transparent: false },
  [BLOCK_TYPES.GRAY_WOOL]: { hardness: 0.8, tool: null, drops: BLOCK_TYPES.GRAY_WOOL, transparent: false },
  [BLOCK_TYPES.LIGHT_GRAY_WOOL]: { hardness: 0.8, tool: null, drops: BLOCK_TYPES.LIGHT_GRAY_WOOL, transparent: false },
  [BLOCK_TYPES.CYAN_WOOL]: { hardness: 0.8, tool: null, drops: BLOCK_TYPES.CYAN_WOOL, transparent: false },
  [BLOCK_TYPES.PURPLE_WOOL]: { hardness: 0.8, tool: null, drops: BLOCK_TYPES.PURPLE_WOOL, transparent: false },
  [BLOCK_TYPES.BLUE_WOOL]: { hardness: 0.8, tool: null, drops: BLOCK_TYPES.BLUE_WOOL, transparent: false },
  [BLOCK_TYPES.BROWN_WOOL]: { hardness: 0.8, tool: null, drops: BLOCK_TYPES.BROWN_WOOL, transparent: false },
  [BLOCK_TYPES.GREEN_WOOL]: { hardness: 0.8, tool: null, drops: BLOCK_TYPES.GREEN_WOOL, transparent: false },
  [BLOCK_TYPES.RED_WOOL]: { hardness: 0.8, tool: null, drops: BLOCK_TYPES.RED_WOOL, transparent: false },
  [BLOCK_TYPES.BLACK_WOOL]: { hardness: 0.8, tool: null, drops: BLOCK_TYPES.BLACK_WOOL, transparent: false },

  // Glass
  [BLOCK_TYPES.GLASS]: { hardness: 0.3, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.WHITE_STAINED_GLASS]: { hardness: 0.3, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.ORANGE_STAINED_GLASS]: { hardness: 0.3, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.MAGENTA_STAINED_GLASS]: { hardness: 0.3, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.LIGHT_BLUE_STAINED_GLASS]: { hardness: 0.3, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.YELLOW_STAINED_GLASS]: { hardness: 0.3, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.LIME_STAINED_GLASS]: { hardness: 0.3, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.PINK_STAINED_GLASS]: { hardness: 0.3, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.GRAY_STAINED_GLASS]: { hardness: 0.3, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.LIGHT_GRAY_STAINED_GLASS]: { hardness: 0.3, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.CYAN_STAINED_GLASS]: { hardness: 0.3, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.PURPLE_STAINED_GLASS]: { hardness: 0.3, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.BLUE_STAINED_GLASS]: { hardness: 0.3, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.BROWN_STAINED_GLASS]: { hardness: 0.3, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.GREEN_STAINED_GLASS]: { hardness: 0.3, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.RED_STAINED_GLASS]: { hardness: 0.3, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.BLACK_STAINED_GLASS]: { hardness: 0.3, tool: null, drops: null, transparent: true },

  // Nether blocks
  [BLOCK_TYPES.NETHERRACK]: { hardness: 0.4, tool: 'pickaxe', drops: BLOCK_TYPES.NETHERRACK, transparent: false },
  [BLOCK_TYPES.NETHER_BRICKS]: { hardness: 2.0, tool: 'pickaxe', drops: BLOCK_TYPES.NETHER_BRICKS, transparent: false },
  [BLOCK_TYPES.CRACKED_NETHER_BRICKS]: { hardness: 2.0, tool: 'pickaxe', drops: BLOCK_TYPES.CRACKED_NETHER_BRICKS, transparent: false },
  [BLOCK_TYPES.CHISELED_NETHER_BRICKS]: { hardness: 2.0, tool: 'pickaxe', drops: BLOCK_TYPES.CHISELED_NETHER_BRICKS, transparent: false },
  [BLOCK_TYPES.NETHER_WART_BLOCK]: { hardness: 1.0, tool: null, drops: BLOCK_TYPES.NETHER_WART_BLOCK, transparent: false },
  [BLOCK_TYPES.WARPED_WART_BLOCK]: { hardness: 1.0, tool: null, drops: BLOCK_TYPES.WARPED_WART_BLOCK, transparent: false },
  [BLOCK_TYPES.SOUL_SAND]: { hardness: 0.5, tool: 'shovel', drops: BLOCK_TYPES.SOUL_SAND, transparent: false },
  [BLOCK_TYPES.SOUL_SOIL]: { hardness: 0.5, tool: 'shovel', drops: BLOCK_TYPES.SOUL_SOIL, transparent: false },
  [BLOCK_TYPES.BASALT]: { hardness: 1.25, tool: 'pickaxe', drops: BLOCK_TYPES.BASALT, transparent: false },
  [BLOCK_TYPES.POLISHED_BASALT]: { hardness: 1.25, tool: 'pickaxe', drops: BLOCK_TYPES.POLISHED_BASALT, transparent: false },
  [BLOCK_TYPES.SMOOTH_BASALT]: { hardness: 1.25, tool: 'pickaxe', drops: BLOCK_TYPES.SMOOTH_BASALT, transparent: false },
  [BLOCK_TYPES.BLACKSTONE]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.BLACKSTONE, transparent: false },
  [BLOCK_TYPES.GILDED_BLACKSTONE]: { hardness: 1.5, tool: 'pickaxe', drops: 'gold_nugget', transparent: false },
  [BLOCK_TYPES.POLISHED_BLACKSTONE]: { hardness: 2.0, tool: 'pickaxe', drops: BLOCK_TYPES.POLISHED_BLACKSTONE, transparent: false },
  [BLOCK_TYPES.CHISELED_POLISHED_BLACKSTONE]: { hardness: 2.0, tool: 'pickaxe', drops: BLOCK_TYPES.CHISELED_POLISHED_BLACKSTONE, transparent: false },
  [BLOCK_TYPES.POLISHED_BLACKSTONE_BRICKS]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.POLISHED_BLACKSTONE_BRICKS, transparent: false },
  [BLOCK_TYPES.CRACKED_POLISHED_BLACKSTONE_BRICKS]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.CRACKED_POLISHED_BLACKSTONE_BRICKS, transparent: false },
  [BLOCK_TYPES.MAGMA_BLOCK]: { hardness: 0.5, tool: 'pickaxe', drops: BLOCK_TYPES.MAGMA_BLOCK, transparent: false },
  [BLOCK_TYPES.CRYING_OBSIDIAN]: { hardness: 50.0, tool: 'pickaxe', drops: BLOCK_TYPES.CRYING_OBSIDIAN, transparent: false },
  [BLOCK_TYPES.OBSIDIAN]: { hardness: 50.0, tool: 'pickaxe', drops: BLOCK_TYPES.OBSIDIAN, transparent: false },
  [BLOCK_TYPES.BEDROCK]: { hardness: -1.0, tool: null, drops: null, transparent: false }, // Unbreakable

  // Liquids
  [BLOCK_TYPES.WATER]: { hardness: 0, tool: null, drops: null, transparent: true, liquid: true },
  [BLOCK_TYPES.LAVA]: { hardness: 0, tool: null, drops: null, transparent: true, liquid: true },

  // Functional blocks
  [BLOCK_TYPES.CRAFTING_TABLE]: { hardness: 2.5, tool: 'axe', drops: BLOCK_TYPES.CRAFTING_TABLE, transparent: false },
  [BLOCK_TYPES.FURNACE]: { hardness: 3.5, tool: 'pickaxe', drops: BLOCK_TYPES.FURNACE, transparent: false },
  [BLOCK_TYPES.CHEST]: { hardness: 2.5, tool: 'axe', drops: BLOCK_TYPES.CHEST, transparent: false },
  [BLOCK_TYPES.ENDER_CHEST]: { hardness: 22.5, tool: 'pickaxe', drops: BLOCK_TYPES.ENDER_CHEST, transparent: false },
  [BLOCK_TYPES.JUKEBOX]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.JUKEBOX, transparent: false },
  [BLOCK_TYPES.ENCHANTING_TABLE]: { hardness: 5.0, tool: 'pickaxe', drops: BLOCK_TYPES.ENCHANTING_TABLE, transparent: false },
  [BLOCK_TYPES.BREWING_STAND]: { hardness: 0.5, tool: 'pickaxe', drops: BLOCK_TYPES.BREWING_STAND, transparent: false },
  [BLOCK_TYPES.CAULDRON]: { hardness: 2.0, tool: 'pickaxe', drops: BLOCK_TYPES.CAULDRON, transparent: false },
  [BLOCK_TYPES.HOPPER]: { hardness: 3.0, tool: 'pickaxe', drops: BLOCK_TYPES.HOPPER, transparent: false },
  [BLOCK_TYPES.DROPPER]: { hardness: 3.5, tool: 'pickaxe', drops: BLOCK_TYPES.DROPPER, transparent: false },
  [BLOCK_TYPES.DISPENSER]: { hardness: 3.5, tool: 'pickaxe', drops: BLOCK_TYPES.DISPENSER, transparent: false },
  [BLOCK_TYPES.PISTON]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.PISTON, transparent: false },
  [BLOCK_TYPES.STICKY_PISTON]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.STICKY_PISTON, transparent: false },
  [BLOCK_TYPES.TNT]: { hardness: 0.0, tool: null, drops: BLOCK_TYPES.TNT, transparent: false },
  [BLOCK_TYPES.BOOKSHELF]: { hardness: 1.5, tool: 'axe', drops: BLOCK_TYPES.BOOKSHELF, transparent: false },
  [BLOCK_TYPES.LECTERN]: { hardness: 2.5, tool: 'axe', drops: BLOCK_TYPES.LECTERN, transparent: false },
  [BLOCK_TYPES.BELL]: { hardness: 5.0, tool: 'pickaxe', drops: BLOCK_TYPES.BELL, transparent: false },
  [BLOCK_TYPES.TARGET]: { hardness: 0.5, tool: null, drops: BLOCK_TYPES.TARGET, transparent: false },
  [BLOCK_TYPES.LOOM]: { hardness: 2.5, tool: 'axe', drops: BLOCK_TYPES.LOOM, transparent: false },
  [BLOCK_TYPES.COMPOSTER]: { hardness: 0.6, tool: 'axe', drops: BLOCK_TYPES.COMPOSTER, transparent: false },
  [BLOCK_TYPES.BARREL]: { hardness: 2.5, tool: 'axe', drops: BLOCK_TYPES.BARREL, transparent: false },
  [BLOCK_TYPES.SMOKER]: { hardness: 3.5, tool: 'pickaxe', drops: BLOCK_TYPES.SMOKER, transparent: false },
  [BLOCK_TYPES.BLAST_FURNACE]: { hardness: 3.5, tool: 'pickaxe', drops: BLOCK_TYPES.BLAST_FURNACE, transparent: false },
  [BLOCK_TYPES.CARTOGRAPHY_TABLE]: { hardness: 2.5, tool: 'axe', drops: BLOCK_TYPES.CARTOGRAPHY_TABLE, transparent: false },
  [BLOCK_TYPES.FLETCHING_TABLE]: { hardness: 2.5, tool: 'axe', drops: BLOCK_TYPES.FLETCHING_TABLE, transparent: false },
  [BLOCK_TYPES.SMITHING_TABLE]: { hardness: 2.5, tool: 'axe', drops: BLOCK_TYPES.SMITHING_TABLE, transparent: false },
  [BLOCK_TYPES.GRINDSTONE]: { hardness: 2.0, tool: 'pickaxe', drops: BLOCK_TYPES.GRINDSTONE, transparent: false },
  [BLOCK_TYPES.STONECUTTER]: { hardness: 3.5, tool: 'pickaxe', drops: BLOCK_TYPES.STONECUTTER, transparent: false },
  [BLOCK_TYPES.NOTE_BLOCK]: { hardness: 0.8, tool: 'axe', drops: BLOCK_TYPES.NOTE_BLOCK, transparent: false },
  [BLOCK_TYPES.IRON_BARS]: { hardness: 5.0, tool: 'pickaxe', drops: BLOCK_TYPES.IRON_BARS, transparent: true },
  [BLOCK_TYPES.CHAIN]: { hardness: 5.0, tool: 'pickaxe', drops: BLOCK_TYPES.CHAIN, transparent: true },
  [BLOCK_TYPES.LADDER]: { hardness: 0.4, tool: 'axe', drops: BLOCK_TYPES.LADDER, transparent: true },
  [BLOCK_TYPES.SCAFFOLDING]: { hardness: 0.0, tool: null, drops: BLOCK_TYPES.SCAFFOLDING, transparent: true },
  [BLOCK_TYPES.LANTERN]: { hardness: 3.5, tool: 'pickaxe', drops: BLOCK_TYPES.LANTERN, transparent: true },
  [BLOCK_TYPES.SOUL_LANTERN]: { hardness: 3.5, tool: 'pickaxe', drops: BLOCK_TYPES.SOUL_LANTERN, transparent: true },
  [BLOCK_TYPES.CAMPFIRE]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.CAMPFIRE, transparent: true },
  [BLOCK_TYPES.SOUL_CAMPFIRE]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.SOUL_CAMPFIRE, transparent: true },
  [BLOCK_TYPES.BEEHIVE]: { hardness: 0.6, tool: 'axe', drops: BLOCK_TYPES.BEEHIVE, transparent: false },
  [BLOCK_TYPES.BEE_NEST]: { hardness: 0.3, tool: null, drops: BLOCK_TYPES.BEE_NEST, transparent: false },
  [BLOCK_TYPES.LODESTONE]: { hardness: 3.5, tool: 'pickaxe', drops: BLOCK_TYPES.LODESTONE, transparent: false },
  [BLOCK_TYPES.RESPAWN_ANCHOR]: { hardness: 50.0, tool: 'pickaxe', drops: BLOCK_TYPES.RESPAWN_ANCHOR, transparent: false },
  [BLOCK_TYPES.LIGHTNING_ROD]: { hardness: 3.0, tool: 'pickaxe', drops: BLOCK_TYPES.LIGHTNING_ROD, transparent: false },
  [BLOCK_TYPES.CONDUIT]: { hardness: 3.0, tool: 'pickaxe', drops: BLOCK_TYPES.CONDUIT, transparent: true },
  [BLOCK_TYPES.BEACON]: { hardness: 3.0, tool: 'pickaxe', drops: BLOCK_TYPES.BEACON, transparent: true },

  // Redstone components
  [BLOCK_TYPES.REDSTONE_WIRE]: { hardness: 0.0, tool: null, drops: 'redstone', transparent: true },
  [BLOCK_TYPES.REDSTONE_TORCH]: { hardness: 0.0, tool: null, drops: BLOCK_TYPES.REDSTONE_TORCH, transparent: true },
  [BLOCK_TYPES.REDSTONE_LAMP]: { hardness: 0.3, tool: null, drops: BLOCK_TYPES.REDSTONE_LAMP, transparent: false },
  [BLOCK_TYPES.REPEATER]: { hardness: 0.0, tool: null, drops: BLOCK_TYPES.REPEATER, transparent: true },
  [BLOCK_TYPES.COMPARATOR]: { hardness: 0.0, tool: null, drops: BLOCK_TYPES.COMPARATOR, transparent: true },
  [BLOCK_TYPES.LEVER]: { hardness: 0.5, tool: null, drops: BLOCK_TYPES.LEVER, transparent: true },
  [BLOCK_TYPES.STONE_BUTTON]: { hardness: 0.5, tool: 'pickaxe', drops: BLOCK_TYPES.STONE_BUTTON, transparent: true },
  [BLOCK_TYPES.OAK_BUTTON]: { hardness: 0.5, tool: 'axe', drops: BLOCK_TYPES.OAK_BUTTON, transparent: true },
  [BLOCK_TYPES.SPRUCE_BUTTON]: { hardness: 0.5, tool: 'axe', drops: BLOCK_TYPES.SPRUCE_BUTTON, transparent: true },
  [BLOCK_TYPES.BIRCH_BUTTON]: { hardness: 0.5, tool: 'axe', drops: BLOCK_TYPES.BIRCH_BUTTON, transparent: true },
  [BLOCK_TYPES.JUNGLE_BUTTON]: { hardness: 0.5, tool: 'axe', drops: BLOCK_TYPES.JUNGLE_BUTTON, transparent: true },
  [BLOCK_TYPES.ACACIA_BUTTON]: { hardness: 0.5, tool: 'axe', drops: BLOCK_TYPES.ACACIA_BUTTON, transparent: true },
  [BLOCK_TYPES.DARK_OAK_BUTTON]: { hardness: 0.5, tool: 'axe', drops: BLOCK_TYPES.DARK_OAK_BUTTON, transparent: true },
  [BLOCK_TYPES.CRIMSON_BUTTON]: { hardness: 0.5, tool: 'axe', drops: BLOCK_TYPES.CRIMSON_BUTTON, transparent: true },
  [BLOCK_TYPES.WARPED_BUTTON]: { hardness: 0.5, tool: 'axe', drops: BLOCK_TYPES.WARPED_BUTTON, transparent: true },
  [BLOCK_TYPES.STONE_PRESSURE_PLATE]: { hardness: 0.5, tool: 'pickaxe', drops: BLOCK_TYPES.STONE_PRESSURE_PLATE, transparent: true },
  [BLOCK_TYPES.OAK_PRESSURE_PLATE]: { hardness: 0.5, tool: 'axe', drops: BLOCK_TYPES.OAK_PRESSURE_PLATE, transparent: true },
  [BLOCK_TYPES.SPRUCE_PRESSURE_PLATE]: { hardness: 0.5, tool: 'axe', drops: BLOCK_TYPES.SPRUCE_PRESSURE_PLATE, transparent: true },
  [BLOCK_TYPES.BIRCH_PRESSURE_PLATE]: { hardness: 0.5, tool: 'axe', drops: BLOCK_TYPES.BIRCH_PRESSURE_PLATE, transparent: true },
  [BLOCK_TYPES.JUNGLE_PRESSURE_PLATE]: { hardness: 0.5, tool: 'axe', drops: BLOCK_TYPES.JUNGLE_PRESSURE_PLATE, transparent: true },
  [BLOCK_TYPES.ACACIA_PRESSURE_PLATE]: { hardness: 0.5, tool: 'axe', drops: BLOCK_TYPES.ACACIA_PRESSURE_PLATE, transparent: true },
  [BLOCK_TYPES.DARK_OAK_PRESSURE_PLATE]: { hardness: 0.5, tool: 'axe', drops: BLOCK_TYPES.DARK_OAK_PRESSURE_PLATE, transparent: true },
  [BLOCK_TYPES.CRIMSON_PRESSURE_PLATE]: { hardness: 0.5, tool: 'axe', drops: BLOCK_TYPES.CRIMSON_PRESSURE_PLATE, transparent: true },
  [BLOCK_TYPES.WARPED_PRESSURE_PLATE]: { hardness: 0.5, tool: 'axe', drops: BLOCK_TYPES.WARPED_PRESSURE_PLATE, transparent: true },
  [BLOCK_TYPES.HEAVY_WEIGHTED_PRESSURE_PLATE]: { hardness: 0.5, tool: 'pickaxe', drops: BLOCK_TYPES.HEAVY_WEIGHTED_PRESSURE_PLATE, transparent: true },
  [BLOCK_TYPES.LIGHT_WEIGHTED_PRESSURE_PLATE]: { hardness: 0.5, tool: 'pickaxe', drops: BLOCK_TYPES.LIGHT_WEIGHTED_PRESSURE_PLATE, transparent: true },
  [BLOCK_TYPES.TRIPWIRE_HOOK]: { hardness: 0.0, tool: null, drops: BLOCK_TYPES.TRIPWIRE_HOOK, transparent: true },
  [BLOCK_TYPES.TRAPPED_CHEST]: { hardness: 2.5, tool: 'axe', drops: BLOCK_TYPES.TRAPPED_CHEST, transparent: false },
  [BLOCK_TYPES.DAYLIGHT_DETECTOR]: { hardness: 0.2, tool: 'axe', drops: BLOCK_TYPES.DAYLIGHT_DETECTOR, transparent: true },
  [BLOCK_TYPES.RAIL]: { hardness: 0.7, tool: 'pickaxe', drops: BLOCK_TYPES.RAIL, transparent: true },
  [BLOCK_TYPES.POWERED_RAIL]: { hardness: 0.7, tool: 'pickaxe', drops: BLOCK_TYPES.POWERED_RAIL, transparent: true },
  [BLOCK_TYPES.DETECTOR_RAIL]: { hardness: 0.7, tool: 'pickaxe', drops: BLOCK_TYPES.DETECTOR_RAIL, transparent: true },
  [BLOCK_TYPES.ACTIVATOR_RAIL]: { hardness: 0.7, tool: 'pickaxe', drops: BLOCK_TYPES.ACTIVATOR_RAIL, transparent: true },

  // Command blocks
  [BLOCK_TYPES.COMMAND_BLOCK]: { hardness: -1.0, tool: null, drops: null, transparent: false }, // Unbreakable in survival
  [BLOCK_TYPES.CHAIN_COMMAND_BLOCK]: { hardness: -1.0, tool: null, drops: null, transparent: false },
  [BLOCK_TYPES.REPEATING_COMMAND_BLOCK]: { hardness: -1.0, tool: null, drops: null, transparent: false },

  // End blocks
  [BLOCK_TYPES.END_STONE]: { hardness: 3.0, tool: 'pickaxe', drops: BLOCK_TYPES.END_STONE, transparent: false },
  [BLOCK_TYPES.END_STONE_BRICKS]: { hardness: 3.0, tool: 'pickaxe', drops: BLOCK_TYPES.END_STONE_BRICKS, transparent: false },
  [BLOCK_TYPES.PURPUR_BLOCK]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.PURPUR_BLOCK, transparent: false },
  [BLOCK_TYPES.PURPUR_PILLAR]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.PURPUR_PILLAR, transparent: false },
  [BLOCK_TYPES.END_ROD]: { hardness: 0.0, tool: null, drops: BLOCK_TYPES.END_ROD, transparent: true },
  [BLOCK_TYPES.DRAGON_EGG]: { hardness: 3.0, tool: null, drops: BLOCK_TYPES.DRAGON_EGG, transparent: true },

  // Slabs and stairs (subset)
  [BLOCK_TYPES.OAK_SLAB]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.OAK_SLAB, transparent: true },
  [BLOCK_TYPES.STONE_SLAB]: { hardness: 2.0, tool: 'pickaxe', drops: BLOCK_TYPES.STONE_SLAB, transparent: true },
  [BLOCK_TYPES.SMOOTH_STONE_SLAB]: { hardness: 2.0, tool: 'pickaxe', drops: BLOCK_TYPES.SMOOTH_STONE_SLAB, transparent: true },
  [BLOCK_TYPES.SANDSTONE_SLAB]: { hardness: 0.8, tool: 'pickaxe', drops: BLOCK_TYPES.SANDSTONE_SLAB, transparent: true },
  [BLOCK_TYPES.COBBLESTONE_SLAB]: { hardness: 2.0, tool: 'pickaxe', drops: BLOCK_TYPES.COBBLESTONE_SLAB, transparent: true },
  [BLOCK_TYPES.BRICK_SLAB]: { hardness: 2.0, tool: 'pickaxe', drops: BLOCK_TYPES.BRICK_SLAB, transparent: true },
  [BLOCK_TYPES.STONE_BRICK_SLAB]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.STONE_BRICK_SLAB, transparent: true },
  [BLOCK_TYPES.NETHER_BRICK_SLAB]: { hardness: 2.0, tool: 'pickaxe', drops: BLOCK_TYPES.NETHER_BRICK_SLAB, transparent: true },
  [BLOCK_TYPES.QUARTZ_SLAB]: { hardness: 0.8, tool: 'pickaxe', drops: BLOCK_TYPES.QUARTZ_SLAB, transparent: true },
  [BLOCK_TYPES.OAK_STAIRS]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.OAK_STAIRS, transparent: true },
  [BLOCK_TYPES.COBBLESTONE_STAIRS]: { hardness: 2.0, tool: 'pickaxe', drops: BLOCK_TYPES.COBBLESTONE_STAIRS, transparent: true },
  [BLOCK_TYPES.BRICK_STAIRS]: { hardness: 2.0, tool: 'pickaxe', drops: BLOCK_TYPES.BRICK_STAIRS, transparent: true },
  [BLOCK_TYPES.STONE_BRICK_STAIRS]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.STONE_BRICK_STAIRS, transparent: true },
  [BLOCK_TYPES.NETHER_BRICK_STAIRS]: { hardness: 2.0, tool: 'pickaxe', drops: BLOCK_TYPES.NETHER_BRICK_STAIRS, transparent: true },
  [BLOCK_TYPES.SANDSTONE_STAIRS]: { hardness: 0.8, tool: 'pickaxe', drops: BLOCK_TYPES.SANDSTONE_STAIRS, transparent: true },

  // Additional blocks
  [BLOCK_TYPES.QUARTZ_BLOCK]: { hardness: 0.8, tool: 'pickaxe', drops: BLOCK_TYPES.QUARTZ_BLOCK, transparent: false },
  [BLOCK_TYPES.CHISELED_QUARTZ_BLOCK]: { hardness: 0.8, tool: 'pickaxe', drops: BLOCK_TYPES.CHISELED_QUARTZ_BLOCK, transparent: false },
  [BLOCK_TYPES.QUARTZ_PILLAR]: { hardness: 0.8, tool: 'pickaxe', drops: BLOCK_TYPES.QUARTZ_PILLAR, transparent: false },
  [BLOCK_TYPES.QUARTZ_BRICKS]: { hardness: 0.8, tool: 'pickaxe', drops: BLOCK_TYPES.QUARTZ_BRICKS, transparent: false },
  [BLOCK_TYPES.SMOOTH_QUARTZ]: { hardness: 2.0, tool: 'pickaxe', drops: BLOCK_TYPES.SMOOTH_QUARTZ, transparent: false },
  [BLOCK_TYPES.PRISMARINE]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.PRISMARINE, transparent: false },
  [BLOCK_TYPES.PRISMARINE_BRICKS]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.PRISMARINE_BRICKS, transparent: false },
  [BLOCK_TYPES.DARK_PRISMARINE]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.DARK_PRISMARINE, transparent: false },
  [BLOCK_TYPES.SEA_LANTERN]: { hardness: 0.3, tool: null, drops: BLOCK_TYPES.SEA_LANTERN, transparent: true },
  [BLOCK_TYPES.SHROOMLIGHT]: { hardness: 1.0, tool: null, drops: BLOCK_TYPES.SHROOMLIGHT, transparent: false },
  [BLOCK_TYPES.HONEY_BLOCK]: { hardness: 0.0, tool: null, drops: BLOCK_TYPES.HONEY_BLOCK, transparent: true },
  [BLOCK_TYPES.HONEYCOMB_BLOCK]: { hardness: 0.6, tool: null, drops: BLOCK_TYPES.HONEYCOMB_BLOCK, transparent: false },
  [BLOCK_TYPES.SLIME_BLOCK]: { hardness: 0.0, tool: null, drops: BLOCK_TYPES.SLIME_BLOCK, transparent: true },
  [BLOCK_TYPES.BONE_BLOCK]: { hardness: 2.0, tool: 'pickaxe', drops: BLOCK_TYPES.BONE_BLOCK, transparent: false },
  [BLOCK_TYPES.NETHERITE_BLOCK]: { hardness: 50.0, tool: 'pickaxe', drops: BLOCK_TYPES.NETHERITE_BLOCK, transparent: false },
  [BLOCK_TYPES.COPPER_BLOCK]: { hardness: 3.0, tool: 'pickaxe', drops: BLOCK_TYPES.COPPER_BLOCK, transparent: false },
  [BLOCK_TYPES.RAW_IRON_BLOCK]: { hardness: 5.0, tool: 'pickaxe', drops: BLOCK_TYPES.RAW_IRON_BLOCK, transparent: false },
  [BLOCK_TYPES.RAW_COPPER_BLOCK]: { hardness: 5.0, tool: 'pickaxe', drops: BLOCK_TYPES.RAW_COPPER_BLOCK, transparent: false },
  [BLOCK_TYPES.RAW_GOLD_BLOCK]: { hardness: 5.0, tool: 'pickaxe', drops: BLOCK_TYPES.RAW_GOLD_BLOCK, transparent: false },
  [BLOCK_TYPES.AMETHYST_BLOCK]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.AMETHYST_BLOCK, transparent: false },
  [BLOCK_TYPES.BUDDING_AMETHYST]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.BUDDING_AMETHYST, transparent: false },
  [BLOCK_TYPES.TINTED_GLASS]: { hardness: 0.3, tool: null, drops: BLOCK_TYPES.TINTED_GLASS, transparent: true },
  [BLOCK_TYPES.POWDER_SNOW]: { hardness: 0.25, tool: 'shovel', drops: BLOCK_TYPES.POWDER_SNOW, transparent: true },
  [BLOCK_TYPES.SCULK]: { hardness: 0.2, tool: 'hoe', drops: BLOCK_TYPES.SCULK, transparent: false },
  [BLOCK_TYPES.SCULK_VEIN]: { hardness: 0.2, tool: 'hoe', drops: null, transparent: true },
  [BLOCK_TYPES.SCULK_CATALYST]: { hardness: 3.0, tool: 'hoe', drops: BLOCK_TYPES.SCULK_CATALYST, transparent: false },
  [BLOCK_TYPES.SCULK_SHRIEKER]: { hardness: 3.0, tool: 'hoe', drops: BLOCK_TYPES.SCULK_SHRIEKER, transparent: false },
  [BLOCK_TYPES.REINFORCED_DEEPSLATE]: { hardness: 55.0, tool: 'pickaxe', drops: BLOCK_TYPES.REINFORCED_DEEPSLATE, transparent: false },
  [BLOCK_TYPES.MANGROVE_LOG]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.MANGROVE_LOG, transparent: false },
  [BLOCK_TYPES.MANGROVE_PLANKS]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.MANGROVE_PLANKS, transparent: false },
  [BLOCK_TYPES.MANGROVE_LEAVES]: { hardness: 0.2, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.BAMBOO_BLOCK]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.BAMBOO_BLOCK, transparent: false },
  [BLOCK_TYPES.STRIPPED_BAMBOO_BLOCK]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.STRIPPED_BAMBOO_BLOCK, transparent: false },
  [BLOCK_TYPES.BAMBOO_PLANKS]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.BAMBOO_PLANKS, transparent: false },
  [BLOCK_TYPES.CHERRY_LOG]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.CHERRY_LOG, transparent: false },
  [BLOCK_TYPES.CHERRY_PLANKS]: { hardness: 2.0, tool: 'axe', drops: BLOCK_TYPES.CHERRY_PLANKS, transparent: false },
  [BLOCK_TYPES.CHERRY_LEAVES]: { hardness: 0.2, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.MOSS_BLOCK]: { hardness: 0.1, tool: 'hoe', drops: BLOCK_TYPES.MOSS_BLOCK, transparent: false },
  [BLOCK_TYPES.BIG_DRIPLEAF]: { hardness: 0.1, tool: 'axe', drops: BLOCK_TYPES.BIG_DRIPLEAF, transparent: true },
  [BLOCK_TYPES.SMALL_DRIPLEAF]: { hardness: 0.0, tool: null, drops: BLOCK_TYPES.SMALL_DRIPLEAF, transparent: true },
  [BLOCK_TYPES.SPORE_BLOSSOM]: { hardness: 0.0, tool: null, drops: BLOCK_TYPES.SPORE_BLOSSOM, transparent: true },
  [BLOCK_TYPES.CAVE_VINES]: { hardness: 0.0, tool: null, drops: 'glow_berries', transparent: true },
  [BLOCK_TYPES.GLOW_LICHEN]: { hardness: 0.2, tool: null, drops: BLOCK_TYPES.GLOW_LICHEN, transparent: true },
  [BLOCK_TYPES.GLOW_BERRIES]: { hardness: 0.0, tool: null, drops: 'glow_berries', transparent: true },
  [BLOCK_TYPES.POINTED_DRIPSTONE]: { hardness: 1.5, tool: 'pickaxe', drops: BLOCK_TYPES.POINTED_DRIPSTONE, transparent: true },
  [BLOCK_TYPES.SCULK_SENSOR]: { hardness: 1.5, tool: 'hoe', drops: BLOCK_TYPES.SCULK_SENSOR, transparent: false },
  [BLOCK_TYPES.CALIBRATED_SCULK_SENSOR]: { hardness: 1.5, tool: 'hoe', drops: BLOCK_TYPES.CALIBRATED_SCULK_SENSOR, transparent: false },
  [BLOCK_TYPES.FROGSPAWN]: { hardness: 0.0, tool: null, drops: null, transparent: true },
  [BLOCK_TYPES.FROG_LIGHT]: { hardness: 0.3, tool: null, drops: BLOCK_TYPES.FROG_LIGHT, transparent: false },
};

// Tool material multipliers for mining speed
const TOOL_MATERIALS = {
  WOOD: { multiplier: 2, durability: 59 },
  STONE: { multiplier: 4, durability: 131 },
  IRON: { multiplier: 6, durability: 250 },
  DIAMOND: { multiplier: 8, durability: 1561 },
  NETHERITE: { multiplier: 9, durability: 2031 },
  GOLD: { multiplier: 12, durability: 32 }, // Fast but low durability
};

// Tool types and their effectiveness
const TOOL_EFFECTIVENESS = {
  pickaxe: ['stone', 'ore', 'metal', 'crystal'],
  axe: ['wood', 'plant', 'organic'],
  shovel: ['dirt', 'sand', 'gravel', 'snow'],
  hoe: ['plant', 'organic', 'sculk'],
  sword: ['plant', 'organic'], // For harvesting
  shears: ['wool', 'plant', 'organic'],
  none: [] // Hand mining
};

const CHUNK_SIZE = 16;
const WORLD_HEIGHT = 256;

module.exports = {
  BLOCK_TYPES,
  BLOCK_PROPERTIES,
  TOOL_MATERIALS,
  TOOL_EFFECTIVENESS,
  CHUNK_SIZE,
  WORLD_HEIGHT,
};